/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlarmToast: typeof import('./src/components/toast/AlarmToast.vue')['default']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BToast: typeof import('bootstrap-vue-next/components/BToast')['BToast']
    HeaderComp: typeof import('./src/components/layout/HeaderComp.vue')['default']
    PasswordInput: typeof import('./src/components/form/PasswordInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortCutComp: typeof import('./src/components/layout/ShortCutComp.vue')['default']
    SideNavComp: typeof import('./src/components/layout/SideNavComp.vue')['default']
  }
}
